apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-downloader-service-account
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: ${GKE_GCP_SA}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-service-account
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: ${GKE_GCP_SA}