apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments.yaml
  - services.yaml
  - serviceaccounts.yaml
  - hpa.yaml
  - postgres-base.yaml

configMapGenerator:
  - name: chats-postgres-init-scripts
    files:
      - db/01-prompts-schema.sql
    options:
      disableNameSuffixHash: true
