apiVersion: v1
kind: Service
metadata:
  name: gcp-exporter
  namespace: dev
  labels:
    app: gcp-exporter
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: metrics
  selector:
    app: gcp-monitoring-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-exporter
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcp-exporter
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcp-exporter
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcp-exporter
subjects:
  - kind: ServiceAccount
    name: gcp-exporter
    namespace: dev
